name: Linter Check
on: [push]
jobs:
  linter-check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo 'export PATH="$HOME/.poetry/bin:$PATH"' >> .zshrc
          make package-install
          make lint