name: Linter Check
on: [push]
jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - name: Linter checks
      - uses: actions/checkout@v2
        run: |
          pip install poetry
          make install
          make lint