name: Linter Check
on: [push]
jobs:
  linter-check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install poetry
          make package-install
          make lint